services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: talkwork
    ports:
      - '3306:3306'
    volumes:
      - tw_mysql:/var/lib/mysql
      - ./server/sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

volumes:
  tw_mysql:
